package com.piinalpin.customsoftdeletes.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import com.piinalpin.customsoftdeletes.entity.base.BaseEntity;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.List;

@EqualsAndHashCode(callSuper = true)
@Data
@Entity
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
@Table(name = "T_TRANSACTION")
public class Transaction extends BaseEntity {

    private static final long serialVersionUID = 6417258128520039672L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(notes = "Generated by database transaction ID")
    private Long id;

    @Column(name = "customer_name", nullable = false)
    @ApiModelProperty(notes = "Customer name")
    private String customerName;

    @Column(name = "transaction_date", nullable = false)
    @ApiModelProperty(notes = "Transaction date")
    private LocalDateTime transactionDate;

    @Column(name = "total_price", nullable = false)
    @ApiModelProperty(notes = "Total price")
    private Integer totalPrice;

    @Column(name = "total_qty", nullable = false)
    @ApiModelProperty(notes = "Total qty")
    private Integer totalQty;

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "transaction")
    private List<TransactionDetail> transactionDetails;

}
